import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.scss";
import Header from "./components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const OpenSauceOne = localFont({
  src: [
    {
      path: '../../public/fonts/open-sauce-one/OpenSauceOne-Black.ttf',
    },
    {
      path: '../../public/fonts/open-sauce-one/OpenSauceOne-BlackItalic.ttf',
    },
    {
      path: '../../public/fonts/open-sauce-one/OpenSauceOne-Bold.ttf',
    },
    {
      path: '../../public/fonts/open-sauce-one/OpenSauceOne-BoldItalic.ttf',
    },
    {
      path: '../../public/fonts/open-sauce-one/OpenSauceOne-ExtraBold.ttf',
    },
    {
      path: '../../public/fonts/open-sauce-one/OpenSauceOne-ExtraBoldItalic.ttf',
    },
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        
        </body>
    </html>
  );
}
